---

- hosts: x.x.x.233
  connection: ssh
  vars:
    cli:
      server: x.x.x.233
      user: yourf5username
      password: yourf5password

  tasks:
    - name: Fetch a qkview from the remote device
      bigip_qkview:
        asm_request_log: yes
        exclude:
          - audit
          - secure
        dest: /var/tmp/
        password: yourf5password
        filename: "{{ item.name }}.qkview"
        server: "{{ item.server }}"
        user: yourf5username
      transport: cli
      ignore_errors: True
      delegate_to: localhost
      with_items:
#        - { server: 'x.x.x.8', name: 'PKB_LB01' }
#        - { server: 'x.x.x.9', name: 'PKB_LB02' }
#        - { server: 'x.x.x.233', name: 'TBS_LB01' }
#        - { server: 'x.x.x.234', name: 'TBS_LB02'}
#        - { server: 'x.x.x.8', name: 'SRB_LB01' }
#        - { server: 'x.x.x.9', name: 'SRB_LB02' }
        - { server: 'x.x.x.8', name: 'MKS_LB01' }
#        - { server: 'x.x.x.9', name: 'MKS_LB02' }
#        - { server: 'x.x.x.9', name: 'SLO_LB01' }
#        - { server: 'x.x.x.10', name: 'SLO_LB02' }

    - name: ngopikeun ucs ka local om..
      shell: scp -r admin@{{ item.server }}:/var/tmp/*.qkview /root/ansible/netadmin/F5/F5_BCK/
      with_items:
        - { server: 'x.x.x.8'}
        - { server: 'x.x.x.9'}
        - { server: 'x.x.x.233'}
        - { server: 'x.x.x.234'}
        - { server: 'x.x.x.8'}
        - { server: 'x.x.x.9'}
        - { server: 'x.x.x.8'}
        - { server: 'x.x.x.9'}
        - { server: 'x.x.x.9'}
        - { server: 'x.x.x.10'}
      delegate_to: localhost
